### ISSUE TITLE
check repositories update

### ISSUE THREAD

**Issue by papajoker** [manjaro/pacman-mirrors#1]
pacman-mirrors do not check repositories update ,  should be an option on the command line (or file .conf) to do research only on white and yellow servers - exclude red (-r --notred)
colors of http://repo.manjaro.org/

**Comment by philmmanjaro** [comment]
Currently this is not possible. We don't check for outdated mirrors yet. pacman-mirrors only checks for speed and country.

**Comment by Kirek** [comment]
We won't add a --nored switch, quoting myself in #17 

> I don't like --nored switch, we already kind of doing this automatically by adding servers with longer than 24h since last sync to the bad server list. In fact I don't like the whole colour thing in pacman-mirrors, even if repo.manjaro.org does that. Keeping with the 3 categories - good, bad(not sync in +24h) and no response is enough.
> The reason is that this may exclude perfectly good mirrors with good ping to some users because they only sync 1-3 times a day. And they are good enough for our users in the default stable branch because they receive updates every week or two.
