### ISSUE TITLE
could use a ranking limiter

### ISSUE THREAD

**Issue by udeved** [manjaro/pacman-mirrors#10]
A very cool feature was to be able to do

```
pacman-mirrors -g -m rank -l 5
```

where -l limits to 5 fastest mirrors instead of ranking full list.
Use case would be in live session to ensure we always start with the fastest mirror regardless of location.

**Comment by Kirek** [comment]
How do you know which are the fastest mirrors if you don't rank all of them previously? This will cut the final result to only 5 mirrors, but you will still need to check every mirror.

**Comment by udeved** [comment]
Right, I know, but the other part is eventually make it easier to match a language or locale against a mirror location. Eg we rename Germany -> DE and so on.
Anyway, the mirror randomizer is not the best solution, with bad luck, you still get slow mirror which makes everything internet related in CAL fragile.

**Comment by philmmanjaro** [comment]
We should use GeoIP like we do with CAL. Simply check how it was done in [locale module](https://github.com/calamares/calamares/commit/3146d2093e8cf429315df73402bd99cc6a2b628f).

**Comment by udeved** [comment]
If @Kirek could take care of it, would be great. :+1:

**Comment by philmmanjaro** [comment]
It is really simple. Simply call http://freegeoip.net/json/ and you get some like this:
```
{"ip":"XX.XX.XXX.XX","country_code":"XX","country_name":"Germany","region_code":"XX","region_name":"Region","city":"City","zip_code":"12345","time_zone":"Timezone","latitude":XX.XXXX,"longitude":YY.YYYY,"metro_code":X}
```
However CVS (http://freegeoip.net/csv) seems to be easier:
```
XX.XX.XXX.XX,XX,Germany,XX,Region,City,12345,Timezone,XX.XX,YY.YY,X
```
Then we simply check if we have a mirror for that Country and only use that for ranking. Simply needs testing ...

**Comment by Kirek** [comment]
Ok, using geoip sounds like a good idea.

**Comment by philmmanjaro** [comment]
However we should make it optional and not enabled by default.

**Comment by udeved** [comment]
I'd also propose we run the ranking with a alpm hook instead of post_install for the package.

**Comment by fhdk** [comment]
This PR https://github.com/manjaro/pacman-mirrors/pull/61 introduce a -f/--fasttrack argument which returns n updated and responsive mirrors

**Comment by fhdk** [comment]
I think this merge solves the issue
https://github.com/manjaro/pacman-mirrors/commit/37890e6e8a6fc68315a6fa40e0ae5006814950cc
