### ISSUE TITLE
Temporarily using a repo to get update fast (feature request)

### ISSUE THREAD

**Issue by now-im** [manjaro/pacman-mirrors#101]
Every manjaro repo has different synchronization time. Sometimes it takes more time than usual. Now we can temporarily use a branch to test a package or update first. but it would be nice to just a repo address to  get the update first.

**Comment by fhdk** [comment]
You can use the 

    sudo pacman-mirrors -b unstable -f 1 -u
    sudo pacman -S package
    sudo pacman-mirrors --geoip -u

This will give 1 up-to-date on all branches mirror and cause pacman to update your databases

**Comment by now-im** [comment]
I have updated my system using -c option. I can't get it out until next testing update hits the repo. The only 4 server had synchronized with testing and I wanted to use one to update the packages. I will try your method in the next update.

**Comment by fhdk** [comment]
If you know the package - you can look it up the complete package on the mirror in question and install it with pacman -U - here is pacman-mirrors as example

    sudo pacman -U http://repo.stdout.net/manjaro/testing/core/x86_64/pacman-mirrors-4.1.3-1-any.pkg.tar.xz

**Comment by now-im** [comment]
This is useful for one package but not a whole the testing batch phlim dumps. For now I think the perfect solution is to use a country whose all server is synchronized to get the update first. 
Besides not a lot of people cares whether they get update couple of hours late or not. 
You can close the issue.

**Comment by fhdk** [comment]
thanks :+1:
