### ISSUE TITLE
Obsolete arguments?

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#104]
@philmmanjaro @Kirek @Huluti @oberon2007 @udeved 

These arguments **can they be removed with 4.2.0-dev**?

- **-d** / **--mirror_dir**
- **-o** / **--output**

Does they have any value at all?

Does any of you know of a place where they are used?

**Comment by philmmanjaro** [comment]
They might be legacy once. Maybe depreciated? @Kirek, @Huluti

**Comment by oberon2007** [comment]
I don't know that they would be used in any script. So don't see a problem if you want to get rid of them :)

**Comment by udeved** [comment]
manjaro-tools don't make use of these parameters.

**Comment by fhdk** [comment]
Thank you for your response.

I take this as an approval of the removal of these arguments.
