### ISSUE TITLE
[manjaro32] add support for new x32 branches

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pacman-mirrors#114]
When we support manjaro32.org we should add the needed x32 branches supported by **pacman-mirrors**. See also: https://github.com/manjaro/release-plan/issues/174

**Comment by philmmanjaro** [comment]
@fhdk: can you check this one?

**Comment by fhdk** [comment]
pacman-mirrors are agnostic to a degree

it should be fairly easy to retrieve the architecture from uname

but are we looking at another mirror pool - downloadable from github?

or how are your thoughts on servicing x32?

**Comment by jonathonf** [comment]
> what does uname -m output on 32-bit system?

`i686`

**Comment by fhdk** [comment]
Released 4.7.0 to unstable

https://github.com/manjaro/pacman-mirrors/commit/4bc97e8eb083df90acc5ba42a219b22d4d6c8ac0
