### ISSUE TITLE
module 'pacman_mirrors.i18n' has no attribute 'language'

### ISSUE THREAD

**Issue by drponti** [manjaro/pacman-mirrors#12]
When trying to update Manjaro, I get this error message:

    sudo pacman-mirrors -g

    Traceback (most recent call last):
      File "/usr/bin/pacman-mirrors", line 26, in <module>
        _ = i18n.language.gettext
    AttributeError: module 'pacman_mirrors.i18n' has no attribute 'language'

**Comment by Huluti** [comment]
Are you still experiencing this issue @drponti ?

**Comment by Huluti** [comment]
No one has encountered this problem: we are closing it for now. Do not hesitate to reopen it if needed.
