### ISSUE TITLE
Sort mirrors on ping and download speed

### ISSUE THREAD

**Issue by Salamandar** [manjaro/pacman-mirrors#120]
I've often found myself with a first mirror with a good (!) ping, but a bad download speed.

Maybe, once the mirrors are ranked by ping, the first ones  could be re-ranked by download speed ? Maybe by downloading package databases as benchmark ?

**Comment by fhdk** [comment]
The mirrors are not ranked by ping.

They are ranked by downloading a small file and the response time is used as rating.
