### ISSUE TITLE
issues with custom mirrorlist

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pacman-mirrors#130]
I just ran
`sudo pacman-mirrors -ic Germany`
and selected the three top listed mirrors.

![3selected](https://user-images.githubusercontent.com/11800714/37687405-ce6f4700-2c9b-11e8-810a-d2eef08dae2c.png)

Feedback:
```
.: INFO User generated mirror list
--------------------------
.: INFO Custom mirror file saved: /var/lib/pacman-mirrors/custom-mirrors.json
.: INFO Writing mirror list
   Germany         : http://mirror.philpot.de/manjaro/unstable/$repo/$arch
   Germany         : http://mirror.philpot.de/manjaro/unstable/$repo/$archunstable/$repo/$arch
.: INFO Mirror list generated and saved to: /etc/pacman.d/mirrorlist
```
As you can see the http philpot mirror is listed twice, once with a link containing `/$archunstable/`, which doesn't seem right. The https link is missing, so is the third mirror.
This is also what **/etc/pacman.d/mirrorlist** actually contains.
Content of **/var/lib/pacman-mirrors/custom-mirrors.json**:
```
[
    {
        "country": "Germany",
        "protocols": [
            "https",
            "http"
        ],
        "url": "http://mirror.philpot.de/manjaro/"
    },
    {
        "country": "Germany",
        "protocols": [
            "https",
            "http"
        ],
        "url": "http://mirror.philpot.de/manjaro/"
    },
    {
        "country": "Germany",
        "protocols": [
            "https"
        ],
        "url": "https://repo.rhindon.net/manjaro/"
    }
]
```
So, the third mirror is listed here, but again philpot http twice, and not the https version.
Another time I had selected two mirrors, ragenet and netzspielplatz and only netzspielplatz got listed. Somehow I cannot reproduce this now, but something seems to not work properly here ...

**Comment by fhdk** [comment]
That is indeed weird

**Comment by fhdk** [comment]
@oberon2007 
That was a nasty one. It has never been in my scenarios that a user would select multiple protocols on the same mirror.

But I nailed it - at least I think so.

**Comment by fhdk** [comment]
Thank you for spotting this.

The condition was indeed not handled properly.

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/releases/tag/4.9.1
