### ISSUE TITLE
Use a better versionning format

### ISSUE THREAD

**Issue by Huluti** [manjaro/pacman-mirrors#18]
Actually versioning of pacman-mirrors seems a bit confused:

- Version is set to 2.0 in some files.
- The package version is 20161101.

I've had a talk with Kirek, here's his suggestion:

> In this case a date is better because we update pacman-mirrors every time we add or remove a mirror, and that would be tagging it everytime all the time.

So, it could be a good idea to unify version to only one versioning format and maybe use Github tags.

What do you think guys?

**Comment by philmmanjaro** [comment]
The package versioning is based on the date we have updated our mirrors. However the program **pacman-mirrors** used a standard versioning. Ask the authors of it ...

**Comment by Huluti** [comment]
I see. So, we have to keep the proper version of the program and the version of the package. The build is directly from git, isn't it?

**Comment by Huluti** [comment]
We now using Github tags.
