### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#19]
When opening interactive mode all server-urls are capped in non obvious places.

What is the idea behind that?

Wouldn't it be better to left-align the list and not cap it?

Also all the mirrors are pre-selected - that somehow goes against the idea of an interactive selection - currently it is more an interactive de-selection :)

Why are interactive mode showing the calculated mirror age when the list is sorted by response time? 

I mean when filtering in pacman-mirrors it is 3 levels - good, resp, bad.

Could we pass the all three lists to the gui and assign then in the order good, resp, bad?

**Comment by Huluti** [comment]
Yes, I'm agree with. Actually, the interactive mode is not perfect. I will propose a better version by this evening.

**Comment by Huluti** [comment]
I have correct some of yours points but not these:

> Why are interactive mode showing the calculated mirror age when the list is sorted by response time?
I mean when filtering in pacman-mirrors it is 3 levels - good, resp, bad.
Could we pass the all three lists to the gui and assign then in the order good, resp, bad?

Because, I prefer to attend to @Kirek's point of view.

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/pull/20

I think the gui cannot be better now :+1:
