### ISSUE TITLE
Error in TTY - display server refuse connection

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#23]
Additional at #21
I would also change 
`query_mirror_state(state_url, mirror_branch, request_timeout, verbose=False)`  the `verbose`  change from optional to required 
`query_mirror_state(state_url, mirror_branch, request_timeout, verbose)`

TTY error - this issue
What is much more interesting is what error is thrown here?
[User screenshot from OP forum ref.](https://forum.manjaro.org/t/unstable-update-2017-01-12-xorg-1-19-gcc-pacman-mirrors/15554/24?u=fhdk)
AFAIK it should not be possible since a `GTK_AVAILABLE` variable is set at launch - which should prevent the --interactive for being launched.

If an error is thrown in tty then I must have made an error? or not?

I checked in tty and I think the variable initializes correct but because its in tty the display server cannot initialize. How do we eliminate this error?

**Comment by Huluti** [comment]
#22: Done 7a9572c ;)

I think that Gtk is available, but since we are in a TTY it can't be launched...

**Comment by fhdk** [comment]
> #21: Done 7a9572c ;)
Yes - i noted - it was a sidenote :)

I think we can prevent the tty error by checking this way

```
term = os.environ.get("TERM")
display = os.environ.get("DISPLAY")
if term == "linux" and display == "":
    self.interactive = False
```

**Comment by fhdk** [comment]
you are rather quick :+1:

**Comment by Kirek** [comment]
2 seconds, probably new record lol

**Comment by papajoker** [comment]
i have also this error in stable V3.0

```
pacman-mirrors -i --geoip
:: Interrogation des serveurs, cela peut prendre quelques temps...
=> Using mirrors in France
Unable to init server: Could not connect: Connection refused
Unable to init server: Impossible de se connecter : Connection refused
Erreur de segmentation (core dumped)
```
normal ! in multi-os , i use systemd-nspawn -> i run this command in a contener.

**Comment by fhdk** [comment]
tir, 17 01 2017 kl. 16:11 -0800, skrev patrick:
> i have also this error in stable V3.0
> pacman-mirrors -i --geoip
> :: Interrogation des serveurs, cela peut prendre quelques temps...
> => Using mirrors in France
> Unable to init server: Could not connect: Connection refused
> Unable to init server: Impossible de se connecter : Connection
> refused
> Erreur de segmentation (core dumped)
> normal ! in multi-os , i use systemd-nspawn -> i run this command in
> a contener.

I don't think the fix has reached production - yet.
But it has been fixed.

If you cannot wait download the sources from the subfolder
pacman_mirrors

* pacman_mirrors.py
* pacman_mirrors_gui.py

Copy the files to /usr/lib/python3.6/site-packages/pacman_mirrors

They will be overwritten when pacman-mirrors 3.1.0 hits the repos
