### ISSUE TITLE
Console UI

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#26]
As an excercise in python I am planning on tinkering with a console ui for --interactive.

I know - why that - but as pointed out 

> [with what options?](https://forum.manjaro.org/t/unstable-update-2017-01-12-xorg-1-19-gcc-pacman-mirrors/15554/8?u=fhdk)

So a console way of launching the `--interactive` option could be fun. 

What do you think?

After poking around on the web I found different approaches and decided to try [urwid](http://urwid.org)

**Comment by Huluti** [comment]
Take a look at [ncurses](https://docs.python.org/3/howto/curses.html).

**Comment by fhdk** [comment]
Closing
