### ISSUE TITLE
Make a review of all strings

### ISSUE THREAD

**Issue by Huluti** [manjaro/pacman-mirrors#27]
I have two propositions:

- Can someone with a good level of English review all the texts displayed in the console?
- Move the non-translatable chars (like "::", "=>",...) from the strings outside the gettext function.

We need to do this to facilitate life of translators and no longer change the sentences all the time.

**Comment by fhdk** [comment]
I could do that. Create a branch, make the review and then PR?

**Comment by Huluti** [comment]
Perfect!

**Comment by fhdk** [comment]
I have made a couple of PRs for review

**Comment by Huluti** [comment]
Close in #28 .
