### ISSUE TITLE
GTK GUI

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#30]
@Huluti 
With my little suggestion in this [PR](https://github.com/manjaro/pacman-mirrors/pull/29), which you have kindly accepted, I found it has an odd behavior but I cannot pinpoint it.

Normally when checking the first server - the commit button becomes active.

Even though I am convinced I only touched strings and rearranged a couple of columns, my code does not activate the commit button.

I have become blind to the code - even when having them side by side.

**Comment by Huluti** [comment]
Already fix in 8174225. Don't worry ;)
