### ISSUE TITLE
Missed one

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#33]
I finshed the Danish translation at Transifex and while doing that I saw this - I remember thinking - need to consolidate them to one - but obviously forgot.

```ERR_SERVER_NOT_REACHABLE = _("Failed to reach server")```
```ERR_SERVER_TIMEOUT = _("Failed to reach the server")```

Good idea for consolidating these two?

**Comment by Huluti** [comment]
Merged thank you!
