### ISSUE TITLE
A little oddity

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#37]
When running without parameters we are informed that a `-g/--generate` is required to to generate a new mirror list.

However, if run with any parameter excluding `-g/--generate` we also generate a new mirror list. 

So it seems the -g/--generate parameter is only required if we want a default mirror list based on `pacman-mirrors.conf`.

But what if I always want to use a specific branch say `unstable`? Then I have 2 choices

- edit `pacman-mirrors.conf` by hand
- always remember to supply the `-b/--branch unstable`

As it is now our specialized choices is not written to `pacman-mirrors.conf` but we have to supply them every time we want to refresh the mirror list. That is if we have chosen to use unstable branch we have to remember that when refreshing the mirror list or we will get errors/warnings when we run `pacman -Syyu`.

From a users POV, wouldn't it be expected that the users personal choices was saved to the configuration file?

When I rewrote the code I assumed - in line with the `-i/--interactive` parameter - that the country selection should be updated in the configuration, and was a bit puzzled when the review contained a remark on this addition.

So I was thinking of expanding the `modify_configuration()` function to write the entire default configuration - not just the custom configuration.

I think it would be an improvement - what do you think of this?

**Comment by Huluti** [comment]
@Kirek what is your opinion?

**Comment by Kirek** [comment]
It's okay, if @philmmanjaro isn't against changing how pacman-mirrors saves the configuration, do it.

**Comment by philmmanjaro** [comment]
Given the current [wiki documentation](https://wiki.manjaro.org/index.php?title=Access_the_Testing_Repositories) we use the **-b** switch only to switch branches temporally. To have it permanent the user has to edit the **/etc/pacman-mirrors.conf** file. However if it is more useful to modify the config with **-b** it is fine with me. However we will loose the temporary function ...

**Comment by fhdk** [comment]
I didn't have that in mind - if the `-b` switch is solely for temporary branch switching then it should not be changed.

I am always on unstable branch and I just wondered why it only is the `Custom` file that is saved in config.

I can live with setting the branch by hand :)

**Comment by fhdk** [comment]
I will close this as it does not seem a good idea.
The best approach is the current where the user generates a custom mirror file and sets the branch manually.
