### ISSUE TITLE
Adding useful info to CONTRIBUTING.md

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#38]
Regarding the virtualenv and virtualenvwrapper I find that some useful info is missing.

I suggested adding info on installation
- `sudo pacman -Syu python-pip`
- `sudo python -m pip install virtualenv virtualenvwrapper`

And adding a link to [virtualenvwrapper docs](https://virtualenvwrapper.readthedocs.io/en/latest/)

**Comment by Huluti** [comment]
91644164e1efbf235df0deee6f946aaa0da2eddc I've just added a link to to virtualenvwrapper. I think it's sufficient. Thank's.
