### ISSUE TITLE
Do we really need to handle two paths for the custom file?

### ISSUE THREAD

**Issue by Huluti** [manjaro/pacman-mirrors#39]
In the file 'scripts/pacman-mirrors' we check if a '/etc/pacman.d/mirrors/Custom' exits and if so we move it to '/var/lib/pacman-mirrors/Custom'. So, I consider that '/var/lib/pacman-mirrors/Custom' is the best path, isn't it? So, why do we take care about the etc folder ? I know that [the wiki](https://wiki.manjaro.org/index.php?title=Create_your_own_Custom_Mirrorlist) says to write a custom mirrorlist in the etc folder. 
Should not one path be encouraged? Did I miss something?

**Comment by Kirek** [comment]
The wiki is outdated, the only valid current path is /var/lib/pacman-mirrors/Custom
The reason we check /etc/pacman.d/mirrors/Custom is because this is where it was saved before, so the script takes care of the migration.

**Comment by Huluti** [comment]
I see. How long has it been changed?

**Comment by Kirek** [comment]
Sometimes since the first big refractor https://github.com/manjaro/pacman-mirrors/commit/b0ddc7ae0092df756b4cde04d99fa78b86767786

**Comment by Huluti** [comment]
I think that we can think to drop its support. We could remove this script and use directly the "pacman_mirrors.py" as an executable.

**Comment by Kirek** [comment]
The stuff under pacman_mirrors is installed like a python module, so invoking it directly can't be done because we need something installed in /usr/bin that's the function of the script.

**Comment by philmmanjaro** [comment]
@Huluti: since we are a rolling release so if needed a conversation function is useful.

**Comment by Huluti** [comment]
@Kirek We can do like in Manjaro-hello: `install -Dm755 src/pacman-mirrors.py $pkgdir/usr/bin/$pkgname`
@philmmanjaro I see but the change has been made 2 years ago. I think it could be discussed.

**Comment by Kirek** [comment]
Both ways to start a python script are fine, we just chose this way, and as it works fine, I don't see any need to change it.
Keeping those lines of code, event when the are legacy on unlikely to be used, cost us nothing, so no need to remove them.
