### ISSUE TITLE
Use default options for the help menu

### ISSUE THREAD

**Issue by Huluti** [manjaro/pacman-mirrors#40]
I have played with the options of the argparse module and I've found something strange: I prefer the way the help is displayed with the default settings (by removing the custom parser). It seems more orderly. I do not think that avoiding the repetition of the parameters is a good thing. With the default way, the syntax is better distinguished.
![help](https://cloud.githubusercontent.com/assets/5782198/22300672/7f809616-e328-11e6-9662-8d99c22f5d51.png)
What do you think?

**Comment by Kirek** [comment]
Well, I added the custom parser because I don't like the repetition of parameters... it felt weird too... the majority of command line tools don't have this kind of repetition

**Comment by Huluti** [comment]
With the current way, for example we can think that '-m' will replace the whole '--method {rank,random}'. Moreover, I think that we are redefining too methods.  Does  just keep _format_action_invocation could be sufficient?

**Comment by Kirek** [comment]
Yes, everything could be deleted but _format_action_invocation, we don't use the rest or are the same as the overrided function.

**Comment by Huluti** [comment]
2895142d84c36386f731e05f782d922e03ac97c7
