### ISSUE TITLE
A couple of small issues slipped my hawkeye

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#42]
https://github.com/fhdk/pacman-mirrors/commit/fcda18a39348c81f9b51651a80b21d902f412f85

2 very small but important things

**Comment by Kirek** [comment]
I send you an invitation so you can have write access to the main repo, so you can push small stuff directly to the main repository.
Still, keep the large changes in pull request or a branch.

**Comment by fhdk** [comment]
søn, 29 01 2017 kl. 07:17 -0800, skrev Ramon Buldó:
> I send you an invitation so you can have write access to the main
> repo, so you can push small stuff directly to the main repository.
> Still, keep the large changes in pull request or a branch.

I will continue with the usual approach :)

Frede Hundewadt
