### ISSUE TITLE
pacman-mirrors to manjaro-mirrors

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#43]
<strike>Since your rewrite of the web-repo-status - I decided to go up against a complete rewrite of pacman-mirrors.

The codename is manjaro-mirrors since it is based on your new data-files.

My intentions is to port the best parts of pacman-mirrors and build the selectable parts on the new data files.

To avoid confusion with pacman-mirrors the conf, data files and custom mirror file is intended to live in /etc/manjaro-mirrors.
</strike>
The idea is 
- save status.json: `S-<timestamp>.json` and if a defined interval has elapsed, update it
- save mirrors.json: `M-<timestamp>.json` and do the same

**thinking-hat**
- a `--save` to write some options to configuration for reuse
- configurable intervals for checking file status
- only do the checking when the app is run by user - no daemon stuff
<strike>
- only basic messages on screen
- verbose as option
- geoip is a must
</strike>
What do you think?

**Comment by Huluti** [comment]
I dont think that a rewrite is a good idea. A rewrite is something not usual and has to be done only if we can't improve the soft (for many possible reasons). We have now a good program that could be improved for sure. Keep up our work on pacman-mirrors! ;)

**Comment by fhdk** [comment]
Thought so :) Is it ok to put the new data-files to use?

the mirrors.json and the status.json

**Comment by fhdk** [comment]
agree

**Comment by Huluti** [comment]
It's the plan ;) Just wait that it's becoming official.
