### ISSUE TITLE
Test the soft before 3.2.0 version

### ISSUE THREAD

**Issue by Huluti** [manjaro/pacman-mirrors#45]
Please test the soft and use as many options as possible to find last bugs before release pacman-mirrors 3.2.0.

**Comment by Huluti** [comment]
@fhdk when I try to launch the tui, I get this error:

> Traceback (most recent call last):
>   File "./pacman_mirrors.py", line 805, in <module>
>     pm.run()
>   File "./pacman_mirrors.py", line 798, in run
>     self.generate_mirror_list_interactive()
>   File "./pacman_mirrors.py", line 293, in generate_mirror_list_interactive
>     interactive = console_ui.run(server_list)
>   File "/home/hugop/Documents/Dev/pacman-mirrors/pacman_mirrors/console_ui.py", line 99, in run
>     app.main()
>   File "/home/hugop/Documents/Dev/pacman-mirrors/pacman_mirrors/console_ui.py", line 66, in main
>     mainform = npyscreen.Form(name=txt.I_TITLE)
>   File "/usr/lib/python3.6/site-packages/npyscreen/fmForm.py", line 37, in __init__
>     super(_FormBase, self).__init__(*args, **keywords)
>   File "/usr/lib/python3.6/site-packages/npyscreen/proto_fm_screen_area.py", line 76, in __init__
>     self.theme_manager = ThemeManagers.ThemeManager()
>   File "/usr/lib/python3.6/site-packages/npyscreen/npysThemeManagers.py", line 70, in __init__
>     self.define_colour_numbers()
>   File "/usr/lib/python3.6/site-packages/npyscreen/npysThemeManagers.py", line 86, in define_colour_numbers
>     if curses.can_change_color():
> _curses.error: must call initscr() first

**Comment by Kirek** [comment]
I have the same error in a tty

**Comment by fhdk** [comment]
I will check it

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/pull/47

Testet and works as expected

**Comment by Kirek** [comment]
https://github.com/manjaro/pacman-mirrors/commit/d373169d1d2e41b1217654ae5d7a230b9da81cac fixed the console ui

**Comment by philmmanjaro** [comment]
How close are we now for a release of this?

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/pull/52
https://github.com/manjaro/pacman-mirrors/pull/53
https://github.com/manjaro/pacman-mirrors/pull/54

**Comment by Huluti** [comment]
@fhdk Very great job! Thank's!
@philmmanjaro I think that we are quite ready. @Kirek are you agree?

**Comment by fhdk** [comment]
I have some minor fixes in PR https://github.com/manjaro/pacman-mirrors/pull/56/

**Comment by Huluti** [comment]
Why do you want to use the new json files in this version? Place of JSON files will soon be changed and we can't use these temporary JSON urls.

**Comment by fhdk** [comment]
I really don't - was just working on the code - I will remove them from this PR

**Comment by Huluti** [comment]
I see ;)

**Comment by Kirek** [comment]
I also agree that 3.2 can be released now.

**Comment by Huluti** [comment]
@Kirek we just need to add npyscreen as a dependency.
