### ISSUE TITLE
I dont understand this

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#50]
When running the current code - I get no server available.

When playing around with the code I discovered that the last_sync is set to 119:47 for all servers?

I went through all the recent commits and I see a simplified last_sync calculation.

You are the experts here what has happened?

**Comment by Huluti** [comment]
Can you revert the commit in local and see if it is better?

**Comment by fhdk** [comment]
Reverting `simplify last_sync calculation` fixes the error

**Comment by Huluti** [comment]
Great! Can you make the commit please?

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/pull/51

**Comment by Huluti** [comment]
Thanks!
