### ISSUE TITLE
handle outdated or dysfunctional mirrors

### ISSUE THREAD

**Issue by oberon2007** [manjaro/pacman-mirrors#58]
Now with the improved [web-repo-interface](http://repo.manjaro.org/new/manjaro-web-repo/docs/index.html) an existing problem becomes even more obvious.
For example, right now, when you look at the mirror state sorted by country, you will notice that you are in a really bad position if you live in Belgium (I used to think that Brussels is not such a remote and lonely location, maybe I was wrong? :stuck_out_tongue_winking_eye: ) and have set pacman-mirrors to use your home country while using testing branch - especially taking into account that sorting by speed might not even save you from your closest mirrors, even if they are totally outdated as they might still respond normally to pacman:

![mirrors](https://cloud.githubusercontent.com/assets/11800714/22734108/d86c13a0-edf4-11e6-827b-30fce4b6d1a8.png)

Should we remove those mirrors from the database? Is there maybe even a way to exclude bad mirrors after a certain amount of days/weeks/months of inactivity?

**Comment by Huluti** [comment]
To use these infos, we have now this file: http://repo.manjaro.org/new/manjaro-web-repo/docs/status.json.

**Comment by fhdk** [comment]
When does this file become official?

**Comment by Huluti** [comment]
https://github.com/manjaro/manjaro-web-repo/issues/19#issuecomment-278737287

**Comment by philmmanjaro** [comment]
I wrote them several times now. No response ...

**Comment by fhdk** [comment]
This PR https://github.com/manjaro/pacman-mirrors/pull/61 introduce a -f/--fasttrack argument which returns n updated and responsive mirrors

**Comment by fhdk** [comment]
I think this merge solves the issue
https://github.com/manjaro/pacman-mirrors/commit/37890e6e8a6fc68315a6fa40e0ae5006814950cc
