### ISSUE TITLE
Mirror in Belarus

### ISSUE THREAD

**Issue by Eudakimau** [manjaro/pacman-mirrors#6]
Can you make Belarus mirror? Thanks!
http://mirror.datacenter.by/pub/mirrors/manjaro/

**Comment by Eudakimau** [comment]
http://mirror.datacenter.by/pub/mirrors/manjaro/

**Comment by Kirek** [comment]
https://github.com/manjaro/pacman-mirrors/commit/19a896bbcf65eb2362b601dea9d036cb85b4594c
