### ISSUE TITLE
What do you think

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#66]
@Huluti @Kirek 
I have been proofreading and proofreading
testet and testet
I think v4 is ready for release

**Comment by fhdk** [comment]
just stumpled on something
pacman-mirrors -c country,country,country -i empty

**Comment by CosmoJG** [comment]
Considering the amount of difficulty I'm having with 3.2.2, yes please. (For some reason, sudo pacman-mirrors -g is creating a mirrorlist with only http://mirrors.cicku.me/manjaro/stable/$repo/$arch in Germany and ftp://kibo.Remind.lu/pub/stable/$repo/$arch in Russia despite the fact that they are two of the slowest on the list and I live far away from both Germany and Russia.) Please release this as soon as possible!
