### ISSUE TITLE
The flaw we discovered

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#71]
**confirmed fix** https://github.com/manjaro/pacman-mirrors/commit/9beda758337e554b6a9b40047f74013e4a70e309

**Temporary solution**
I have succesfully recreated the issue on my machine and the only way to escape that faulty mirrorlist is

    sudo pacman-mirrors -i -m random

Then select mirrors and save the list.

https://forum.manjaro.org/t/pacman-mirrors-mirrorlist-issue/19905

**Comment by philmmanjaro** [comment]
Is this only with the current **v4.0** series or did that already happened in our **v3.2** series.

**Comment by fhdk** [comment]
@philmmanjaro 
It happened in the 3.x.x series somewhere.

It is related to to the 98h thing we have when sorting mirrors.
I have made change to 3.2.2 in txt.py which I have confirmed removed the flaw

**Comment by Ste74** [comment]
Yep also in italian forum users report this issue.. 
So the 3.2.2 is ok ?

**Comment by philmmanjaro** [comment]
I've pushed out the fixed versions now. Please test and confirm it working. I also removed those outdated mirrors.

**Comment by philmmanjaro** [comment]
Fixed within **pacman-mirrorlist-20170319-1**.

**Comment by fhdk** [comment]
Both works as expected

**Comment by philmmanjaro** [comment]
@fhdk: thx for the fix. How stable is **v4.0** series anyway?

**Comment by fhdk** [comment]
Very stable - I have been doing a lot of tests with different arguments and combinations and it works as expected - those who have installed it and responded have been positive and there has been no malfunctions I know off. I think if some had met malfunctions - they would probably have responded.

@Huluti had one but I could not recreate it.

In every scenario I have tested it works as expected.

**Comment by philmmanjaro** [comment]
Good to know @fhdk. I've tested the main functions and it works. We might release it as **pacman-mirrors** soon and replace the **pacman-mirrorlist** package. @Huluti and @Kirek: did you guys found time to review it yet?

**Comment by Huluti** [comment]
@fhdk has done such a great job, has taken his time to fix many bugs and has received positive returns from users of the forum. I've review the code and it sounds good. I think that we are ready.

**Comment by philmmanjaro** [comment]
@fhdk: please check once more the code and tell me if still some needs to be added. If not, ping me and we make a **4.0.x-stable** branch and release it as **v4.0-final** to our community.

**Comment by fhdk** [comment]
will do :+1:

**Comment by fhdk** [comment]
@philmmanjaro  @Huluti 
I have checked it once again. :+1: And I have nothing to add.
I have been coding long enough to know that nothing is sure until a 100 people use it on a daily basis :)
I have added 2 files to the test folder.
One bash-script which runs scenarios and a testpoints.md with a reference of what to lookout for.

Could you have a look at the testpoints.md and see if a scenario/usecase comes too mind?
