### ISSUE TITLE
[pacman-mirrors-gui] add a sort function

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pacman-mirrors#72]
Every graphical UI is able to sort the list. Can we do that also within the gtk UI?

**Comment by Huluti** [comment]
Yes, I'll take care of that.

**Comment by Huluti** [comment]
Here's the initial support: 5772933defcb38be6fcffaf919099ea95d1880af.
With this, we can just sort Countries and URLs columns.

**Comment by Huluti** [comment]
Don't send it in stable, it has a bug.

**Comment by Huluti** [comment]
It's now fixed by 6b19d43df4062903c8e052d2eb578bead445b2db. I just have to find the better way to enable sorting on the sync column.

**Comment by Huluti** [comment]
It should be ready.

**Comment by fhdk** [comment]
@Huluti @philmmanjaro 
Do you know a simple way to get pygobject support in virtualenv?
Another thought
Does the sorting reflect in the actual write to mirrorlist or is just for selection purpose?
I mean - why bother ranking the mirrors before selecting them if the sorting is changed by the user?
