### ISSUE TITLE
Nice sorting feature

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#74]
I like that - it has good potential

Another thought
The sorting reflect in the actual write to mirrorlist.
I mean - why bother ranking the mirrors before selecting them when the sorting is changed afterwards?

**Comment by Huluti** [comment]
You're right, but I don't see how to handle that. An idea?

**Comment by fhdk** [comment]
I think it can be with a oneliner based on the random var and it must be done just before the call to output_mirrorlist

⁣Sendt af TypeApp ​

Den 20. mar. 2017 19.09, fra 19.09, Hugo Posnic <notifications@github.com> skrev:
>You're right, but I don't see how to handle that. An idea?
>
>--
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/pacman-mirrors/issues/74#issuecomment-287848474

I think it can be with a oneliner based on the random var and it must be done just before the call to output_mirrorlist
Sendt af http://www.typeapp.com/r?b=9203 TypeApp
Den 20. mar. 2017, fra 19.09, Hugo Posnic < mailto:notifications@github.com notifications@github.com
> skrev:
You're right, but I don't see how to handle that. An idea?

**Comment by fhdk** [comment]
@Huluti 
>You're right, but I don't see how to handle that. An idea?
Sort the list in the done() call.

    self.custom_list = sorted(self.custom_list, key=itemgetter("resp_time"))

But it kind of depends on what result a user expect from output - does the user expect the mirrorlist to be sorted the he/she chooses or the way it ways intended?

Could we create a checkbox which defaults to the intention and if the user unchecks we leave it as is ordered?

**Comment by Huluti** [comment]
I think that sorting in GUI is just useful to make easier to find mirrors but not to sort mirrors in output.

**Comment by fhdk** [comment]
Then in the `done()` call.

```
if not self.random:
    self.custom_list = sorted(self.custom_list, key=itemgetter("resp_time"))
else:
   shuffle(self.custom_list)
```

**Comment by Huluti** [comment]
Done db4dc7f588ff400767939c13bbfc2b726b8f4cee. Thank's @fhdk!

**Comment by fhdk** [comment]
you're welcome

**Comment by fhdk** [comment]
@Huluti 
Is this unevitable pickup heat?

**Comment by fhdk** [comment]
@Huluti @philmmanjaro 
You know the same thing is almost impossible in TUI?

**Comment by Huluti** [comment]
I have no idea...

**Comment by Huluti** [comment]
[Sorry, I don't understand your sentence...](https://github.com/manjaro/pacman-mirrors/issues/74#issuecomment-287866698)

**Comment by fhdk** [comment]
Traceback (most recent call last):
  File "/media/sources/manjaro/pacman-mirrors/pacman_mirrors/graphicalui.py", line 134, in done
    if self.random:
AttributeError: 'GraphicalUI' object has no attribute 'random'

**Comment by fhdk** [comment]
https://github.com/manjaro/pacman-mirrors/commit/188e81294e7e4af8ca2b1619d3d568db397b2650

**Comment by fhdk** [comment]
Traceback (most recent call last):
  File "/media/sources/manjaro/pacman-mirrors/pacman_mirrors/graphicalui.py", line 137, in done
    shuffle(self.custom_list)
NameError: name 'shuffle' is not defined

**Comment by fhdk** [comment]
fixed https://github.com/manjaro/pacman-mirrors/commit/86b782413143eb8703f5f7cb01a23531a8cbd10f
