### ISSUE TITLE
Be more tolerant when typing countries with -c option

### ISSUE THREAD

**Issue by Huluti** [manjaro/pacman-mirrors#77]
Maybe we should be more tolerant when the user types the country list by accept spaces, comma,... and don't be case sensitive?

**Comment by fhdk** [comment]
I have thought of it

The case thing is not a problem

The split string has to be consistent - either or - not both

**Comment by Huluti** [comment]
I think at least we could accept lowercase countries.

**Comment by fhdk** [comment]
In danish we have an expression which - google translated - goes like this 'it becomes a slippery slope'.

I don't know how that saying works in other languages but my point is - where does it end?

* da: Frankrig en: France 
* da: Danmark en: Denmark 
* da: Sverige en: Sweden ?

**Comment by fhdk** [comment]
Doing something else and found a way to use both comma and space as separator between countryies
https://github.com/manjaro/pacman-mirrors/commit/1351b0c29043f6c639a97bd5f17c39ca08e525d9
