### ISSUE TITLE
"Method" key in pacman-mirros.conf file is not read 

### ISSUE THREAD

**Issue by guinux** [manjaro/pacman-mirrors#8]
"pacman-mirrors -g" command always use rank method even if "random" is written in /etc/pacman-mirrors.conf. The error is that option is not read by the parse_configuration_file function.
"pacman-mirrors-g -m random" command works as expected.

**Comment by Kirek** [comment]
Fixed via https://github.com/manjaro/pacman-mirrors/commit/71af9262c4b879e1672cb904f54cc2d0fb06c890
