### ISSUE TITLE
A scripting API

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#81]
One packager @udeved  has sent a wish for some kind of scripting API.

Can it be done without confusing end users with a never ending list of options and arguments?

E.g. an api to manipulate branch - though this is very close to the -b argument
all that needs to be done is write it to pacman-mirrors.conf.

Reverse is even easier since this is default behavior - reading the branch from pacman-mirrors.conf and generating the mirrorlist accordingly.

**Comment by udeved** [comment]
Just asking, I do this currently with get and set functions in manjaro-tools, but I would come in handy, if this was possible with pacman-mirrors itself.
Use case would be in calamares for example, or manjaro-tools

**Comment by fhdk** [comment]
ideas good and bad

- [ ] get branch
- [ ] set branch

**Comment by fhdk** [comment]
Still like some feedback - or in light of recent improvements - should it be thrown away?

**Comment by udeved** [comment]
get/set branch methods would be really cool feature, eg in chroot.

**Comment by fhdk** [comment]
How do you intend to use it?
What do you expect?

**Comment by udeved** [comment]
Consider this code snippet from chroot-run script:

```bash
[[ -n $mirrors_conf ]] && cp ${mirrors_conf} "$1/etc/pacman-mirrors.conf"

    if [[ -n ${build_mirror} ]];then
        build_mirror=${build_mirror}'/$repo/$arch'
        if ${keep_mirrors}; then
            set_branch "$1" "$(get_branch $1)"
        else
            echo "Server = ${build_mirror}" > "$1/etc/pacman.d/mirrorlist"
        fi
    else
        set_branch "$1" "$(get_branch $1)"
    fi
```

Would be of similar use in calamares with python. I would just call pacman-mirrors instead of manipulating its conf file.

**Comment by fhdk** [comment]
I am so lost in shell scripting

What does this do? Translated to my brain :smile:

**Comment by udeved** [comment]
Ah ok, it copied a pacman-mirrors.conf in chroot, then gets the branch specified in build script, and set the desired branch in chroot.

**Comment by fhdk** [comment]
are you trying to tell me that you read - somehow - the specified - branch from pacman-mirrors.conf?

**Comment by fhdk** [comment]
You mention build-script - is this different than pacman-mirrors.conf or does it read it or ....

**Comment by fhdk** [comment]
and how does it get the 'desired branch'

**Comment by udeved** [comment]
No, Its about chroot access and creation independently what branch the host system uses.
Example:

I want to build a package for stable branch, but I run unstable on host.
So I specify branch in build script, and the scipt manipulates the chroot/etc/pacman-mirrors.conf branch var.

**Comment by fhdk** [comment]
so you want to run pacman-mirrors in chroot and have it somehow manipulate the branch in the chroot

**Comment by fhdk** [comment]
that is if anyone was to call this api - it would manipulate their own pacman-mirrors.conf accordingly?

**Comment by udeved** [comment]
I would just love to have an option where pacman-mirrors is capable to read and write the branch in /etc/pacman-mirrirs.conf

**Comment by fhdk** [comment]
I get it - you want pacman-mirrors to be able to change the branch setting in any environment?

**Comment by fhdk** [comment]
I can do that - how do we proceed

**Comment by udeved** [comment]
Say pacman-mirrors -G returns currently set branch, and pacman-mirrors -S unstable, stes the branch.

**Comment by fhdk** [comment]
capital -G and capital -S
I will play with it

**Comment by udeved** [comment]
Just randomly picked letters, I take what you implement. :)

**Comment by fhdk** [comment]
oh no - i get it **G**et and **S**et

**Comment by fhdk** [comment]
for my testing you'll get -GB -SB

**Comment by udeved** [comment]
Fine too. 👍

**Comment by udeved** [comment]
Or -bset and -bget or so 🤣

**Comment by fhdk** [comment]
No need for reset - like '# Branch = stable'

**Comment by udeved** [comment]
Would hurt, but I haven't needed this.
My host is unstable, and I build pkg and iso for all 3 branches.

**Comment by fhdk** [comment]
which one should have precedense - in case of both present as arguments.

I think you will get one entry point with either set or get

**Comment by fhdk** [comment]
How do you want the return value?

**Comment by fhdk** [comment]
pacman-mirrors -bapi set <branch>
pacman-mirrors -bapi get <branch>

**Comment by udeved** [comment]
Hmm, we currently have a -b arg, but afaik its not permanent.

Two calls for -G and -S would be fine.But -S should ebentually optionally accept -f options

**Comment by fhdk** [comment]
so you expect the set option to execute the mirrorlist generation

**Comment by fhdk** [comment]
lets use -a/--api

**Comment by udeved** [comment]
Ig thats possible, would be great. 

I could get branch, and set branch and optionally rank mirrors, which is not necessary in chroot, but nice to have to play around with. 
Currently I set a single build mirror in chroot mirrorlist and then restore default mirrorlist on iso.

**Comment by fhdk** [comment]
so 

`-a get` returns the branch in pure text - eg. stable

`-a set <branch>` writes branch to pacman-mirrors.conf and executes pacman-mirrrors -what

**Comment by fhdk** [comment]
I think you would be better off with a second call to pacman-mirrors with whatever options you desire

**Comment by udeved** [comment]
and the absolute addition after these, a --root arg similar to pacman.
pacman-mirrors -G --root $chroot

**Comment by fhdk** [comment]
now your are disturbing - I don't speak shell

**Comment by udeved** [comment]
Similar to ... 
`man pacman`

> -r, --root <path>
>            Specify an alternative installation root (default is /). This should not be used as a way to install
>            software into /usr/local instead of /usr. This option is used if you want to install a package on a
>            temporarily mounted partition that is "owned" by another system.  NOTE: If database path or log 
>

**Comment by fhdk** [comment]
sorry - I wouldn't know to connect an action to it - and what that action is supposed to do - the shell thing?

**Comment by fhdk** [comment]
Really - when I say I don't understand shell - I  don't - very very basic understanding yes - but the level you trying to pull up on - sorry - no.

**Comment by fhdk** [comment]
I am very aware of some of my limitations and shell scripting - tried to help @Chrysostomus - had to give in.

**Comment by udeved** [comment]
Its easily explained, --root would simply set in your python script $mnt/etc/pacman.d/mirrorlist
and $mnt/etc/pacman-mirrors.conf.

$mnt is a variable path.

In scripting, like shell, php and perl, $var gets you the content of var="foo"

you can try it in terminal

`myvar='foo'; echo "${myvar}"`

**Comment by fhdk** [comment]
so - you want to be able to supply pm with a path of which to write the mirrorlist or the conf

the mirrorlist is already available as -o/--output

**Comment by udeved** [comment]
ah, ok, seems similar

**Comment by fhdk** [comment]
so you would like an -c/--config option to dump the branch to the imaginary path?

**Comment by udeved** [comment]
wouldn't a prefix simplify things in code? Dunno.
If I supplied --root /mnt everything conf related was prefixed with /mnt

**Comment by fhdk** [comment]
As long as I know what to expect in arguments - I think it is possible to handle everything

**Comment by fhdk** [comment]
it is the unexpected that breaks things

**Comment by fhdk** [comment]
I could do that ...

**Comment by udeved** [comment]
I think you would end up with perhaps one arg less with -r/--root

Ideally, we would implement the branch stuff in pacman directly, which already has --root arg.

**Comment by fhdk** [comment]
you see - hadn't I challenged you

**Comment by fhdk** [comment]
I don't know how argparse will handle /mnt but I'll begin from this

**Comment by fhdk** [comment]
actually - I think no problem - backwards to -o/--output - handles /

**Comment by udeved** [comment]
Oh, the idea to patch pacman is quite old, but I already have too many little projects going.

**Comment by fhdk** [comment]
Its late for me now - going offline :smile_cat:

**Comment by fhdk** [comment]
the more specific you get - the better

**Comment by fhdk** [comment]
I have an idea for a flow - I can handle your $mnt variable - no problem
the following arguments is added:

* `-a/--api`
* `--prefix`
* `--set-branch {True,False}`
* `--get-branch {True,False}`
  - a positive integer above 0 is fail, this api use negative integer
    - stable -1
    - testing -2
    - unstable -3

* **`-a/--api`** is trigger for `--prefix, --set-branch, --get-branch`

The presence of an api request is placed as the last check in the initial internal setup. That means that configuration has been read and the internal config object is fully populated.

* Supply branch with `-b/--branch`
* `--get-branch` and `--set-branch` are mutually exclusive.
  - If `-b/--branch` is present as argument `--get-branch` is ignored.

So example
```
pacman-mirrors -b unstable -f 10 --api --prefix $mnt
```
* fasttrack mirrorlist of 10
* mirrorlist is pointing to unstable branch
* mirrorlist path is prefixed with `$mnt` eg. `/mnt/install`
* mirrorlist is written to `/mnt/install/etc/pacman.d/mirrorlist`
```
pacman-mirrors -b testing --geoip -m random --prefix /mnt/setup --set-branch
```
* a mirrorlist with either one country or a randomized mirrorlist
* mirrorlist is pointing to `testing` branch
* the rest is ignored as `--api` is missing
```
pacman-mirrors -b testing --geoip -m random --api --prefix /mnt/setup --get-branch
```
* pacman-mirrors does nothing but return the value of pacman-mirrors `Branch = `

**Comment by fhdk** [comment]
@udeved 
Try build from my master branch https://github.com/fhdk/pacman-mirrors/commit/04e2f97cd283fbfc5eb0acc6ec61e922c2d098d3 and see if it behaves like you think/intend

**Comment by fhdk** [comment]
@udeved Look here for api
https://github.com/manjaro/pacman-mirrors/issues/81#issuecomment-290649717
