### ISSUE TITLE
--interactive

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#84]
In terminator under openbox pacman-mirrors --interactive is generating a message I do not quite understand.

Maybe you know what this means

```
(pacman-mirrors:1138): Gtk-WARNING **: Allocating size to pacman_mirrors+graphicalui+GraphicalUI 0x1fa6290 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by fhdk** [comment]
It has no impact on runtime - I was just curios and I have read up on Gtk

**Comment by Huluti** [comment]
I've try to find what it is this message but I haven't found anything relevant. In this case, I think it's only appearing on openbox.
