### ISSUE TITLE
Somethings wrong now

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#87]
`-i --default` loads no mirrors

@Huluti 
it was working yesterday
and if I revert the changes from last night it works as expected

There is a shell-script and a checklist for outputs in tests folder.
I have reverted some of your changes since I couldn't find the culprit.

**Comment by fhdk** [comment]
whatever was wrong is fixed now
commit https://github.com/manjaro/pacman-mirrors/commit/ea5033e79ac865d1dc46b816c2a2bf60bf7b6095

**Comment by Huluti** [comment]
So you have revert all? I think that there was good changes. What do you think?

**Comment by fhdk** [comment]
I am sorry - There were some really good simplifications of expression all-right but I first tried reverting one by one but I couldn't find the culprit so I had to revert everything - but I will go through the commits and add your changes - OK?

**Comment by Huluti** [comment]
No probllem at all. I understand :). Just add them one by one when you'll have some time.

**Comment by fhdk** [comment]
Do you have an idea to how I test the shell return value from api.

It returns -n where n er 1,2,3 depending on branch in config

I use sys.exit(-1) for stable

How do I check this value from a shell script?

**Comment by Huluti** [comment]
I have no idea... sorry.

**Comment by fhdk** [comment]
sys.exit(self.config["branch"])

```
#!/usr/bin/env bash

BRANCH=$( (pacman-mirrors --api --get-branch >&1) 2>&1 )
echo ${BRANCH}
```

**Comment by fhdk** [comment]
@Huluti 
Your good changes is back and I found not why but where the code failed.
That one I have not used :smile_cat:

**Comment by fhdk** [comment]
@Huluti 
Can you build an upload a new pacman-mirrors-dev package?

**Comment by Huluti** [comment]
I don't have this power yet. ☹ Hope @philmmanjaro will do.
