### ISSUE TITLE
Is v4.0.3 ready to be used in production?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pacman-mirrors#88]
Hi Team,

we are close to **v17.0.1** release of Manjaro in general. One of the updates would be **pacman-mirrors** replacing **pacman-mirrorlist**. So my question is: Are we ready for it with **v4.0.3**?

**Comment by Huluti** [comment]
Yes, it is.

**Comment by fhdk** [comment]
I would dare say 4.1 is ready

**Comment by fhdk** [comment]
maybe not - too optimistic
