### ISSUE TITLE
Release of 4.1 branch

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#92]
@philmmanjaro 
I you can agree - I think we should create a release of 4.1

**Comment by fhdk** [comment]
@philmmanjaro 
I have been thinking about the issue today with manjaro.org.

Not long time went by before user asking question regarding pacman-mirrors complaining about network connection despite the user having internet connection.

I am thinking of adding one more network check againts eg. main github.com which only is run if manjaro.org fails.

**Comment by fhdk** [comment]
I have pushed the change to 4.1 as well
https://github.com/manjaro/pacman-mirrors/commit/ca4218d4bda7952eac7cdc2049afb12392ed2662

**Comment by fhdk** [comment]
@philmmanjaro 
So shamed - I push an error - an exit(0) which was for my test - It is corrected

**Comment by philmmanjaro** [comment]
I've pushed out some [new packages](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170501/011122.html).

**Comment by fhdk** [comment]
Added a convenience feature https://github.com/manjaro/pacman-mirrors/commit/229090ac77c092c30fe08a8063bd7f9826e1aeea
