### ISSUE TITLE
Badly ordered servers

### ISSUE THREAD

**Issue by participante0** [manjaro/pacman-mirrors#95]
**OS:** Manjaro JWM 17.0.1 Gellivara
**Kernel:** Linux 4.9.24-1-MANJARO x86_64
**Software:** pacman-mirrors 4.0.4-1
**Branch:** stable

Steps to reproduce it:
1. `sudo pacman-mirrors -g -t 5`
```
   1.619 South_Africa   : http://mirror.is.co.za/mirrors/manjaro.org/
   2.213 Sweden         : https://ftp.lysator.liu.se/pub/manjaro/
   1.355 Spain          : http://ftp.caliu.cat/manjaro/
   2.451 Sweden         : http://mirror.zetup.net/manjaro/
   1.617 Taiwan         : http://free.nchc.org.tw/manjaro/
```
A server in Spain is between 2 servers in Sweden.

**Comment by fhdk** [comment]
This is not a bug.
The order in which the servers are tested is irrelevant.
The final mirror list will be ordered by response time.
